apiVersion: v2
name: cockroachdb
version: 2.0.1
appVersion: 22.1.4
description: Multi-k8s cockroach deployment
sources:
  - https://github.com/cockroachdb/cockroach
dependencies:
- name: reloader
  version: "v0.0.118"
  repository: "https://stakater.github.io/stakater-charts"
